site_name: å¤§æ¨¡å‹æ•°æ®åŠ©æ‰‹
nav:
    - ğŸ  é¦–é¡µ: index.md
    - âš™ï¸ ç¯å¢ƒé…ç½®: environment.md
    - ğŸš€ å¿«é€Ÿä½“éªŒ: quick-start.md
    - ğŸ› ï¸ æœ¬åœ°å¼€å‘: local-development.md
    - â„¹ï¸ å¸¸è§é—®é¢˜: faq.md

# ä»£ç ä»“åº“ä¿¡æ¯
repo_name: apconw/sanic-web # ä»“åº“åç§°
repo_url: https://github.com/apconw/sanic-web


theme:
  name: material
  language: en # é»˜è®¤è¯­è¨€
  features: # åŠŸèƒ½
    - announce.dismiss # å¯ä»¥å‰æ‰å…¬å‘Šçš„åŠŸèƒ½
    - content.action.edit # ç¼–è¾‘æŒ‰é’®ï¼Œä¼¼ä¹æ²¡å•¥ç”¨
    - content.action.view # æŸ¥çœ‹æŒ‰é’®ï¼Œä¼¼ä¹æ²¡å•¥ç”¨
    - content.code.annotate # ä»£ç æ³¨é‡Šï¼Œå…·ä½“ä¸æ¸…æ¥š
    - content.code.copy # å¤åˆ¶ä»£ç æŒ‰é’®
    - content.tooltips # ä¸å¤ªæ¸…æ¥šå‘¢è¿™ä¸ª
    - navigation.expand # é»˜è®¤å±•å¼€å¯¼èˆªæ 

plugins:
  - tags
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - i18n: # å¤šè¯­è¨€æ’ä»¶
      docs_structure: suffix # æŠ„æ¥çš„ï¼Œä¸å¤ªæ‡‚
      fallback_to_default: true # æŠ„æ¥çš„ï¼Œä¸å¤ªæ‡‚
      reconfigure_material: true # æŠ„æ¥çš„ï¼Œä¸å¤ªæ‡‚
      reconfigure_search: true # æŠ„æ¥çš„ï¼Œä¸å¤ªæ‡‚
      languages: # å¤šè¯­è¨€é…ç½® - éœ€è¦å°å¿ƒä¸€ç‚¹
        - locale: en
          default: true # é»˜è®¤è¯­è¨€
          name: English
          build: true # æ˜¯å¦æ„å»º
        - locale: zh
          name: ç®€ä½“ä¸­æ–‡

  # ç‰ˆæƒä¿¡æ¯
copyright: Copyright &copy; 2025 apconw